// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-behind-every-high-performing-influencer-campaign-e4fa4c23/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-behind-every-high-performing-influencer-campaign-e4fa4c23/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-behind-every-high-performing-influencer-campaign-e4fa4c23/ix.json";

export const metadata: Metadata = {
  title: "Behind Every High-Performing Influencer Campaign",
  description: "Explore valuable insights, fresh perspectives, and practical ideas that keep you informed, inspired, and ready for what’s ahead.",
  openGraph: {
    title: "Behind Every High-Performing Influencer Campaign",
    description: "Explore valuable insights, fresh perspectives, and practical ideas that keep you informed, inspired, and ready for what’s ahead.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009e/6aa634567b55c753b1614ad0_image%2019287.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/behind-every-high-performing-influencer-campaign"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/behind-every-high-performing-influencer-campaign"} />
      <SiteFooter currentPath={"/blogs/behind-every-high-performing-influencer-campaign"} />
      <PageInteractions payload={ixPayload} route={"/blogs/behind-every-high-performing-influencer-campaign"} />
    </>
  );
}
