// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import OurServicesSection from "@/components/sites/relab-0c02b053/services-3b1aeccb/OurServicesSection";
import FaqSection from "@/components/sites/relab-0c02b053/services-3b1aeccb/FaqSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/services-3b1aeccb/ix.json";

export const metadata: Metadata = {
  title: "Services - Relab Webflow HTML Website Template",
  description: "Present your expertise with the Relab Services page, a modern Webflow layout designed to showcase your services, capabilities, solutions, and value.",
  openGraph: {
    title: "Services - Relab Webflow HTML Website Template",
    description: "Present your expertise with the Relab Services page, a modern Webflow layout designed to showcase your services, capabilities, solutions, and value.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/services"} />
      <OurServicesSection />
      <FaqSection />
      <SiteCta currentPath={"/services"} />
      <SiteFooter currentPath={"/services"} />
      <PageInteractions payload={ixPayload} route={"/services"} />
    </>
  );
}
