// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import StudyInfoSection from "@/components/sites/relab-0c02b053/case-studies-nova-ai-assistant-c78a9cc4/StudyInfoSection";
import CaseDetailSection from "@/components/sites/relab-0c02b053/case-studies-nova-ai-assistant-c78a9cc4/CaseDetailSection";
import OurTalentSection from "@/components/sites/relab-0c02b053/case-studies-nova-ai-assistant-c78a9cc4/OurTalentSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/case-studies-nova-ai-assistant-c78a9cc4/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-nova-ai-assistant-c78a9cc4/ix.json";

export const metadata: Metadata = {
  title: "Nova AI Assistant",
  description: "Strategic creator partnerships showcased real product use cases, helping the brand build trust and accelerate user acquisition.",
  openGraph: {
    title: "Nova AI Assistant",
    description: "Strategic creator partnerships showcased real product use cases, helping the brand build trust and accelerate user acquisition.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009e/6aad106baf4b67d2946bfce7_Frame%202147262233%20(6).avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies/nova-ai-assistant"} />
      <StudyInfoSection />
      <CaseDetailSection />
      <OurTalentSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/case-studies/nova-ai-assistant"} />
      <SiteFooter currentPath={"/case-studies/nova-ai-assistant"} />
      <PageInteractions payload={ixPayload} route={"/case-studies/nova-ai-assistant"} />
    </>
  );
}
