// Generated by scripts/convert-page.mjs from the captured reference markup.
import "./critical.css";
import SiteHeader from "@/components/sites/adeel-site/shared/SiteHeader";
import ContactSection from "@/components/sites/adeel-site/contact-4eb95063/ContactSection";
import SiteCta from "@/components/sites/adeel-site/shared/SiteCta";
import SiteFooter from "@/components/sites/adeel-site/shared/SiteFooter";
import PageInteractions from "@/components/sites/adeel-site/shared/PageInteractions";
import ixPayload from "@/components/sites/adeel-site/contact-4eb95063/ix.json";
import { buildMetadata } from "@/lib/metadata";

/**
 * Metadata for `/contact`.
 *
 * Built through `buildMetadata` so it inherits the canonical URL, the share
 * image, the icon set and the robots directives from one source. The inline
 * object this replaced carried its own copy of the Open Graph block and pointed
 * `images` at `/assets/shared/thumbnail-2.jpg` -- a template placeholder that
 * reads "PLACE YOUR DESIGN HERE".
 */
export const metadata = buildMetadata({
  title: "Contact — Sayyad Adeel Ahmad",
  description:
    "Get in touch with Sayyad Adeel Ahmad about a project, an idea, or just to say hello. The contact form is the fastest way to reach him.",
  path: "/contact",
});

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/contact"} />
      <ContactSection />
      <SiteCta currentPath={"/contact"} />
      <SiteFooter currentPath={"/contact"} />
      <PageInteractions payload={ixPayload} route={"/contact"} />
    </>
  );
}
