// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import ContactSection from "@/components/sites/relab-0c02b053/contact-4eb95063/ContactSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/contact-4eb95063/ix.json";

export const metadata: Metadata = {
  title: "Contact - Relab Webflow HTML Website Template",
  description: "Connect with potential clients through the Relab Contact page, a polished Webflow layout designed for inquiries, contact details, and clear calls to action.",
  openGraph: {
    title: "Contact - Relab Webflow HTML Website Template",
    description: "Connect with potential clients through the Relab Contact page, a polished Webflow layout designed for inquiries, contact details, and clear calls to action.",
    images: ["/assets/shared/thumbnail-2.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/contact"} />
      <ContactSection />
      <SiteCta currentPath={"/contact"} />
      <SiteFooter currentPath={"/contact"} />
      <PageInteractions payload={ixPayload} route={"/contact"} />
    </>
  );
}
