// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import StudyInfoSection from "@/components/sites/relab-0c02b053/case-studies-brew-blend-launch-bb3d83b2/StudyInfoSection";
import CaseDetailSection from "@/components/sites/relab-0c02b053/case-studies-brew-blend-launch-bb3d83b2/CaseDetailSection";
import OurTalentSection from "@/components/sites/relab-0c02b053/case-studies-brew-blend-launch-bb3d83b2/OurTalentSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/case-studies-brew-blend-launch-bb3d83b2/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-brew-blend-launch-bb3d83b2/ix.json";

export const metadata: Metadata = {
  title: "Brew & Blend Launch",
  description: "A creator-driven product launch that sparked conversations, increased brand awareness, and generated strong organic engagement on TikTok.",
  openGraph: {
    title: "Brew & Blend Launch",
    description: "A creator-driven product launch that sparked conversations, increased brand awareness, and generated strong organic engagement on TikTok.",
    images: ["/assets/case-studies/01-case-studies/frame-2147262233-5.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies/brew-blend-launch"} />
      <StudyInfoSection />
      <CaseDetailSection />
      <OurTalentSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/case-studies/brew-blend-launch"} />
      <SiteFooter currentPath={"/case-studies/brew-blend-launch"} />
      <PageInteractions payload={ixPayload} route={"/case-studies/brew-blend-launch"} />
    </>
  );
}
