// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import SectionSection from "@/components/sites/relab-0c02b053/style-guide-43f6bc9a/SectionSection";
import StyleGuideSection from "@/components/sites/relab-0c02b053/style-guide-43f6bc9a/StyleGuideSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/style-guide-43f6bc9a/ix.json";

export const metadata: Metadata = {
  title: "Style Guide - Relab Webflow HTML Website Template",
  description: "Explore the Relab style guide for a clear reference to typography, colors, buttons, forms, components, and reusable design elements across the template.",
  openGraph: {
    title: "Style Guide - Relab Webflow HTML Website Template",
    description: "Explore the Relab style guide for a clear reference to typography, colors, buttons, forms, components, and reusable design elements across the template.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/style-guide"} />
      <SectionSection />
      <StyleGuideSection />
      <SiteCta currentPath={"/style-guide"} />
      <SiteFooter currentPath={"/style-guide"} />
      <PageInteractions payload={ixPayload} route={"/style-guide"} />
    </>
  );
}
