// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import StudyInfoSection from "@/components/sites/relab-0c02b053/case-studies-movefit-challenge-596acd2d/StudyInfoSection";
import CaseDetailSection from "@/components/sites/relab-0c02b053/case-studies-movefit-challenge-596acd2d/CaseDetailSection";
import OurTalentSection from "@/components/sites/relab-0c02b053/case-studies-movefit-challenge-596acd2d/OurTalentSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/case-studies-movefit-challenge-596acd2d/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-movefit-challenge-596acd2d/ix.json";

export const metadata: Metadata = {
  title: "MoveFit Challenge",
  description: "A multi-platform creator campaign designed to increase community participation and product visibility.",
  openGraph: {
    title: "MoveFit Challenge",
    description: "A multi-platform creator campaign designed to increase community participation and product visibility.",
    images: ["/assets/case-studies/01-case-studies/frame-2147262233-4.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies/movefit-challenge"} />
      <StudyInfoSection />
      <CaseDetailSection />
      <OurTalentSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/case-studies/movefit-challenge"} />
      <SiteFooter currentPath={"/case-studies/movefit-challenge"} />
      <PageInteractions payload={ixPayload} route={"/case-studies/movefit-challenge"} />
    </>
  );
}
