// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import SectionSection from "@/components/sites/relab-0c02b053/licenses-91c6e809/SectionSection";
import LicenseSection from "@/components/sites/relab-0c02b053/licenses-91c6e809/LicenseSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/licenses-91c6e809/ix.json";

export const metadata: Metadata = {
  title: "License - Relab Webflow HTML Website Template",
  description: "Review the Relab license information to understand the permitted use, customization, and distribution terms for this Webflow website template and assets.",
  openGraph: {
    title: "License - Relab Webflow HTML Website Template",
    description: "Review the Relab license information to understand the permitted use, customization, and distribution terms for this Webflow website template and assets.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/licenses"} />
      <SectionSection />
      <LicenseSection />
      <SiteCta currentPath={"/licenses"} />
      <SiteFooter currentPath={"/licenses"} />
      <PageInteractions payload={ixPayload} route={"/licenses"} />
    </>
  );
}
