// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import CaseStudiesSection from "@/components/sites/relab-0c02b053/case-studies-cecbd40a/CaseStudiesSection";
import OurClientsSection from "@/components/sites/relab-0c02b053/case-studies-cecbd40a/OurClientsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-cecbd40a/ix.json";

export const metadata: Metadata = {
  title: "Case Studies - Relab Webflow HTML Website Template",
  description: "Showcase your best work with Relab Case Studies, a polished Webflow layout designed to present projects, results, processes, and creative work.",
  openGraph: {
    title: "Case Studies - Relab Webflow HTML Website Template",
    description: "Showcase your best work with Relab Case Studies, a polished Webflow layout designed to present projects, results, processes, and creative work.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies"} />
      <CaseStudiesSection />
      <OurClientsSection />
      <SiteCta currentPath={"/case-studies"} />
      <SiteFooter currentPath={"/case-studies"} />
      <PageInteractions payload={ixPayload} route={"/case-studies"} />
    </>
  );
}
