// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-short-video-trends-that-will-dominate-this-year-aa27f5ee/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-short-video-trends-that-will-dominate-this-year-aa27f5ee/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-short-video-trends-that-will-dominate-this-year-aa27f5ee/ix.json";

export const metadata: Metadata = {
  title: "Short Video Trends That Will Dominate This Year",
  description: "Explore insightful blog articles, expert perspectives, and practical ideas designed to inform, inspire, and help you discover new strategies and trends.",
  openGraph: {
    title: "Short Video Trends That Will Dominate This Year",
    description: "Explore insightful blog articles, expert perspectives, and practical ideas designed to inform, inspire, and help you discover new strategies and trends.",
    images: ["/assets/blogs/01-blog/cover-size-image-frame-2147262476.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/short-video-trends-that-will-dominate-this-year"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/short-video-trends-that-will-dominate-this-year"} />
      <SiteFooter currentPath={"/blogs/short-video-trends-that-will-dominate-this-year"} />
      <PageInteractions payload={ixPayload} route={"/blogs/short-video-trends-that-will-dominate-this-year"} />
    </>
  );
}
