// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import AboutHeroSection from "@/components/sites/relab-0c02b053/about-979bddc4/AboutHeroSection";
import OurValuesSection from "@/components/sites/relab-0c02b053/about-979bddc4/OurValuesSection";
import OurTeamSection from "@/components/sites/relab-0c02b053/about-979bddc4/OurTeamSection";
import WorksAwardWithTeamSection from "@/components/sites/relab-0c02b053/about-979bddc4/WorksAwardWithTeamSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/about-979bddc4/ix.json";

export const metadata: Metadata = {
  title: "About - Relab Webflow HTML Website Template",
  description: "Tell your story with the Relab About page, a clean Webflow layout designed to showcase your brand, team, values, experience, and creative approach.",
  openGraph: {
    title: "About - Relab Webflow HTML Website Template",
    description: "Tell your story with the Relab About page, a clean Webflow layout designed to showcase your brand, team, values, experience, and creative approach.",
    images: ["/assets/shared/thumbnail-2.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/about"} />
      <AboutHeroSection />
      <OurValuesSection />
      <OurTeamSection />
      <WorksAwardWithTeamSection />
      <SiteCta currentPath={"/about"} />
      <SiteFooter currentPath={"/about"} />
      <PageInteractions payload={ixPayload} route={"/about"} />
    </>
  );
}
