// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-turning-creator-content-into-brand-growth-5e2bc6dd/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-turning-creator-content-into-brand-growth-5e2bc6dd/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-turning-creator-content-into-brand-growth-5e2bc6dd/ix.json";

export const metadata: Metadata = {
  title: "Turning Creator Content Into Brand Growth",
  description: "Discover fresh ideas, expert insights, and practical strategies to help you stay informed, inspired, and ahead of what’s next.",
  openGraph: {
    title: "Turning Creator Content Into Brand Growth",
    description: "Discover fresh ideas, expert insights, and practical strategies to help you stay informed, inspired, and ahead of what’s next.",
    images: ["/assets/blogs/01-blog/frame-2147262476-1.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/turning-creator-content-into-brand-growth"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/turning-creator-content-into-brand-growth"} />
      <SiteFooter currentPath={"/blogs/turning-creator-content-into-brand-growth"} />
      <PageInteractions payload={ixPayload} route={"/blogs/turning-creator-content-into-brand-growth"} />
    </>
  );
}
