// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import OursServicesSection from "@/components/sites/relab-0c02b053/services-campaign-management-338c55b0/OursServicesSection";
import ServicesSlideSection from "@/components/sites/relab-0c02b053/services-campaign-management-338c55b0/ServicesSlideSection";
import FaqSection from "@/components/sites/relab-0c02b053/services-campaign-management-338c55b0/FaqSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/services-campaign-management-338c55b0/ix.json";

export const metadata: Metadata = {
  title: "Campaign Management",
  description: "End-to-end campaign execution including creator outreach, timelines, approvals, publishing, and performance reporting.",
  openGraph: {
    title: "Campaign Management",
    description: "End-to-end campaign execution including creator outreach, timelines, approvals, publishing, and performance reporting.",
    images: ["/assets/home/05-solutions-slider/frame-2147238602-1.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/services/campaign-management"} />
      <OursServicesSection />
      <ServicesSlideSection />
      <FaqSection />
      <SiteCta currentPath={"/services/campaign-management"} />
      <SiteFooter currentPath={"/services/campaign-management"} />
      <PageInteractions payload={ixPayload} route={"/services/campaign-management"} />
    </>
  );
}
