// Generated by scripts/convert-page.mjs. The reference site serves the
// /404 markup for every unmatched URL, so Next's not-found boundary reuses it.
import type { Metadata } from "next";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import FourGroSection from "@/components/sites/relab-0c02b053/404-316556f0/FourGroSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/404-316556f0/ix.json";

export const metadata: Metadata = {
  title: "404 - Relab Webflow HTML Website Template",
};

export default function NotFound() {
  return (
    <>
      <SiteHeader currentPath={"/404"} />
      <FourGroSection />
      <SiteCta currentPath={"/404"} />
      <SiteFooter currentPath={"/404"} />
      <PageInteractions payload={ixPayload} route={"/404"} />
    </>
  );
}
