// Generated by scripts/convert-page.mjs. The reference site serves the
// /404 markup for every unmatched URL, so Next's not-found boundary reuses it.
import SiteHeader from "@/components/sites/adeel-site/shared/SiteHeader";
import FourGroSection from "@/components/sites/adeel-site/404-316556f0/FourGroSection";
import SiteCta from "@/components/sites/adeel-site/shared/SiteCta";
import SiteFooter from "@/components/sites/adeel-site/shared/SiteFooter";
import PageInteractions from "@/components/sites/adeel-site/shared/PageInteractions";
import ixPayload from "@/components/sites/adeel-site/404-316556f0/ix.json";
import { buildMetadata } from "@/lib/metadata";

/**
 * Metadata for Next's not-found boundary.
 *
 * Every unmatched URL renders this. It is marked `noindex` so the error page is
 * never indexed regardless of which URL the crawler arrived on.
 */
export const metadata = buildMetadata({
  title: "Page not found — Sayyad Adeel Ahmad",
  description:
    "That page doesn't exist. Head back to the homepage to see projects, experiments and notes, or get in touch via the contact page.",
  path: "/404",
  noIndex: true,
});

export default function NotFound() {
  return (
    <>
      <SiteHeader currentPath={"/404"} />
      <FourGroSection />
      <SiteCta currentPath={"/404"} />
      <SiteFooter currentPath={"/404"} />
      <PageInteractions payload={ixPayload} route={"/404"} />
    </>
  );
}
