// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import OursServicesSection from "@/components/sites/relab-0c02b053/services-short-form-video-production-10486cad/OursServicesSection";
import ServicesSlideSection from "@/components/sites/relab-0c02b053/services-short-form-video-production-10486cad/ServicesSlideSection";
import FaqSection from "@/components/sites/relab-0c02b053/services-short-form-video-production-10486cad/FaqSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/services-short-form-video-production-10486cad/ix.json";

export const metadata: Metadata = {
  title: "Short-Form Video Production",
  description: "Create engaging vertical videos tailored for today&#x27;s fastest-growing platforms. From creative direction to final delivery, we produce content that captures attention and drives results.",
  openGraph: {
    title: "Short-Form Video Production",
    description: "Create engaging vertical videos tailored for today&#x27;s fastest-growing platforms. From creative direction to final delivery, we produce content that captures attention and drives results.",
    images: ["/assets/home/05-solutions-slider/frame-2147238602-3.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/services/short-form-video-production"} />
      <OursServicesSection />
      <ServicesSlideSection />
      <FaqSection />
      <SiteCta currentPath={"/services/short-form-video-production"} />
      <SiteFooter currentPath={"/services/short-form-video-production"} />
      <PageInteractions payload={ixPayload} route={"/services/short-form-video-production"} />
    </>
  );
}
