// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import OursServicesSection from "@/components/sites/relab-0c02b053/services-creator-partnerships-0af462f4/OursServicesSection";
import ServicesSlideSection from "@/components/sites/relab-0c02b053/services-creator-partnerships-0af462f4/ServicesSlideSection";
import FaqSection from "@/components/sites/relab-0c02b053/services-creator-partnerships-0af462f4/FaqSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/services-creator-partnerships-0af462f4/ix.json";

export const metadata: Metadata = {
  title: "Creator Partnerships",
  description: "We connect your brand with carefully selected creators whose audience, style, and voice align with your campaign objectives.",
  openGraph: {
    title: "Creator Partnerships",
    description: "We connect your brand with carefully selected creators whose audience, style, and voice align with your campaign objectives.",
    images: ["/assets/home/05-solutions-slider/cover-size-image-frame-2147238602.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/services/creator-partnerships"} />
      <OursServicesSection />
      <ServicesSlideSection />
      <FaqSection />
      <SiteCta currentPath={"/services/creator-partnerships"} />
      <SiteFooter currentPath={"/services/creator-partnerships"} />
      <PageInteractions payload={ixPayload} route={"/services/creator-partnerships"} />
    </>
  );
}
