// Generated by scripts/convert-page.mjs from the captured reference markup.
import "./critical.css";
import SiteHeader from "@/components/sites/adeel-site/shared/SiteHeader";
import FourGroSection from "@/components/sites/adeel-site/404-316556f0/FourGroSection";
import SiteCta from "@/components/sites/adeel-site/shared/SiteCta";
import SiteFooter from "@/components/sites/adeel-site/shared/SiteFooter";
import PageInteractions from "@/components/sites/adeel-site/shared/PageInteractions";
import ixPayload from "@/components/sites/adeel-site/404-316556f0/ix.json";
import { buildMetadata } from "@/lib/metadata";

/**
 * Metadata for the explicit `/404` route.
 *
 * `noIndex` matters more here than anywhere else: this URL returns HTTP 404 by
 * design, and without `noindex` a crawler that reaches it directly can still
 * index the error page as site content.
 */
export const metadata = buildMetadata({
  title: "Page not found — Sayyad Adeel Ahmad",
  description:
    "That page doesn't exist. Head back to the homepage to see projects, experiments and notes, or get in touch via the contact page.",
  path: "/404",
  noIndex: true,
});

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/404"} />
      <FourGroSection />
      <SiteCta currentPath={"/404"} />
      <SiteFooter currentPath={"/404"} />
      <PageInteractions payload={ixPayload} route={"/404"} />
    </>
  );
}
