// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import FourGroSection from "@/components/sites/relab-0c02b053/404-316556f0/FourGroSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/404-316556f0/ix.json";

export const metadata: Metadata = {
  title: "404 - Relab Webflow HTML Website Template",
  description: "The page you’re looking for could not be found. Return to the Relab website to explore services, case studies, blogs, pricing, contact information, and more.",
  openGraph: {
    title: "404 - Relab Webflow HTML Website Template",
    description: "The page you’re looking for could not be found. Return to the Relab website to explore services, case studies, blogs, pricing, contact information, and more.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/404"} />
      <FourGroSection />
      <SiteCta currentPath={"/404"} />
      <SiteFooter currentPath={"/404"} />
      <PageInteractions payload={ixPayload} route={"/404"} />
    </>
  );
}
