// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import SectionSection from "@/components/sites/relab-0c02b053/changelog-9433db80/SectionSection";
import ChangelogSection from "@/components/sites/relab-0c02b053/changelog-9433db80/ChangelogSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/changelog-9433db80/ix.json";

export const metadata: Metadata = {
  title: "Changelog - Relab Webflow HTML Website Template",
  description: "View the Relab changelog for a clear record of template updates, improvements, fixes, new features, and other changes across different releases and versions.",
  openGraph: {
    title: "Changelog - Relab Webflow HTML Website Template",
    description: "View the Relab changelog for a clear record of template updates, improvements, fixes, new features, and other changes across different releases and versions.",
    images: ["/assets/shared/thumbnail-2.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/changelog"} />
      <SectionSection />
      <ChangelogSection />
      <SiteCta currentPath={"/changelog"} />
      <SiteFooter currentPath={"/changelog"} />
      <PageInteractions payload={ixPayload} route={"/changelog"} />
    </>
  );
}
