// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-choosing-the-right-kocs-for-your-next-campaign-13b11efb/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-choosing-the-right-kocs-for-your-next-campaign-13b11efb/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-choosing-the-right-kocs-for-your-next-campaign-13b11efb/ix.json";

export const metadata: Metadata = {
  title: "Choosing The Right KOCs For Your Next Campaign",
  description: "Stay ahead with expert perspectives, emerging trends, and practical insights that turn ideas into meaningful opportunities.",
  openGraph: {
    title: "Choosing The Right KOCs For Your Next Campaign",
    description: "Stay ahead with expert perspectives, emerging trends, and practical insights that turn ideas into meaningful opportunities.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009e/6aa63490df53d8544603abca_image%2019269.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/choosing-the-right-kocs-for-your-next-campaign"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/choosing-the-right-kocs-for-your-next-campaign"} />
      <SiteFooter currentPath={"/blogs/choosing-the-right-kocs-for-your-next-campaign"} />
      <PageInteractions payload={ixPayload} route={"/blogs/choosing-the-right-kocs-for-your-next-campaign"} />
    </>
  );
}
