// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogSection from "@/components/sites/relab-0c02b053/blogs-adf7f5aa/BlogSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-adf7f5aa/ix.json";

export const metadata: Metadata = {
  title: "Blogs - Relab Webflow HTML Website Template",
  description: "Share ideas and insights with the Relab Blogs page, a flexible Webflow CMS layout designed for publishing articles, stories, updates, and useful content.",
  openGraph: {
    title: "Blogs - Relab Webflow HTML Website Template",
    description: "Share ideas and insights with the Relab Blogs page, a flexible Webflow CMS layout designed for publishing articles, stories, updates, and useful content.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs"} />
      <BlogSection />
      <SiteCta currentPath={"/blogs"} />
      <SiteFooter currentPath={"/blogs"} />
      <PageInteractions payload={ixPayload} route={"/blogs"} />
    </>
  );
}
