// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-how-to-work-viewers-in-the-first-3-seconds-ac2e25e9/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-how-to-work-viewers-in-the-first-3-seconds-ac2e25e9/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-how-to-work-viewers-in-the-first-3-seconds-ac2e25e9/ix.json";

export const metadata: Metadata = {
  title: "How To Work Viewers In The First 3 Seconds",
  description: "Dive into insightful articles, industry trends, and proven strategies crafted to spark ideas and drive better decisions.",
  openGraph: {
    title: "How To Work Viewers In The First 3 Seconds",
    description: "Dive into insightful articles, industry trends, and proven strategies crafted to spark ideas and drive better decisions.",
    images: ["/assets/home/15-insights-ideas/frame-2147262476-2.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/how-to-work-viewers-in-the-first-3-seconds"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/how-to-work-viewers-in-the-first-3-seconds"} />
      <SiteFooter currentPath={"/blogs/how-to-work-viewers-in-the-first-3-seconds"} />
      <PageInteractions payload={ixPayload} route={"/blogs/how-to-work-viewers-in-the-first-3-seconds"} />
    </>
  );
}
