/**
 * header-section — shared by every page of the site.
 *
 * Webflow's only per-page variation is which anchors it marked
 * `aria-current="page"` / `w--current`, so the marking is derived from
 * `currentPath` instead of being duplicated into 25 copies of the markup.
 *
 * Generated by scripts/convert-page.mjs.
 */
export default function SiteHeader({ currentPath }: { currentPath: string }) {
  return (
    <section data-wf--header-section--variant={"base"} data-wf-component-id={"24ca57b6-65bd-90cf-29f6-88f79a1acfa1"} data-wf-variant-state={"base"} className={"header-section"}>
      <div data-animation={"default"} data-collapse={"medium"} data-duration={"400"} data-easing={"ease"} data-easing2={"ease"} role={"banner"} className={"navbar w-nav"}>
        <div className={"nav-content-wrap"}>
          <div className={"container w-container"}>
            <div className={"nav-inner"}>
              <a href={"/"} className={`nav-logo-link w-nav-brand${currentPath === "/" ? " w--current" : ""}`} aria-current={currentPath === "/" ? "page" : undefined}>
                <img loading={"lazy"} src={"/assets/shared/relab.svg"} alt={"Brand Logo"} className={"nav-logo"} />
              </a>
              <div className={"nav-manus-wrapper"}>
                <a href={"/about"} className={`nav-link w-inline-block${currentPath === "/about" ? " w--current" : ""}`} aria-current={currentPath === "/about" ? "page" : undefined}>
                  <div>About</div>
                </a>
                <a href={"/services"} className={`nav-link w-inline-block${currentPath === "/services" ? " w--current" : ""}`} aria-current={currentPath === "/services" ? "page" : undefined}>
                  <div>Services</div>
                </a>
                <a href={"/case-studies"} className={`nav-link w-inline-block${currentPath === "/case-studies" ? " w--current" : ""}`} aria-current={currentPath === "/case-studies" ? "page" : undefined}>
                  <div>Case Studies</div>
                </a>
                <a href={"/blogs"} className={`nav-link w-inline-block${currentPath === "/blogs" ? " w--current" : ""}`} aria-current={currentPath === "/blogs" ? "page" : undefined}>
                  <div>Blog</div>
                </a>
              </div>
              <div menu-bar-toggle={"true"} className={"nav-menu-wrap"}>
                <div menu-bar={"true"} className={"menu-wrapper"}>
                  <div className={"menu-wrap"}>
                    <div id={"w-node-_61536114-f853-7b8f-27e5-49cf2f79f3f8-9a1acfa1"} className={"menu-one"}>
                      <a data-wf--text-button--variant={"base"} href={"/"} className={`text-button w-inline-block${currentPath === "/" ? " w--current" : ""}`} aria-current={currentPath === "/" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Home</div>
                        <div className={"text-button-hover-text"}>Home</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/about"} className={`text-button w-inline-block${currentPath === "/about" ? " w--current" : ""}`} aria-current={currentPath === "/about" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>About</div>
                        <div className={"text-button-hover-text"}>About</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/services"} className={`text-button w-inline-block${currentPath === "/services" ? " w--current" : ""}`} aria-current={currentPath === "/services" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Services</div>
                        <div className={"text-button-hover-text"}>Services</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/case-studies"} className={`text-button w-inline-block${currentPath === "/case-studies" ? " w--current" : ""}`} aria-current={currentPath === "/case-studies" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Case Studies</div>
                        <div className={"text-button-hover-text"}>Case Studies</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/blogs"} className={`text-button w-inline-block${currentPath === "/blogs" ? " w--current" : ""}`} aria-current={currentPath === "/blogs" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Blog</div>
                        <div className={"text-button-hover-text"}>Blog</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/pricing"} className={`text-button w-inline-block${currentPath === "/pricing" ? " w--current" : ""}`} aria-current={currentPath === "/pricing" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Pricing</div>
                        <div className={"text-button-hover-text"}>Pricing</div>
                      </a>
                      <a data-wf--text-button--variant={"base"} href={"/contact"} className={`text-button w-inline-block${currentPath === "/contact" ? " w--current" : ""}`} aria-current={currentPath === "/contact" ? "page" : undefined}>
                        <div className={"text-button-normal-text"}>Contact</div>
                        <div className={"text-button-hover-text"}>Contact</div>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className={"nav-button-wrap"}>
                <a btn-anim={"true"} data-wf--button--variant={"base"} data-wf-component-id={"90522a0b-8143-769f-2ad2-e28710708494"} data-wf-variant-state={"base"} href={"/contact"} className={`button w-inline-block${currentPath === "/contact" ? " w--current" : ""}`} aria-current={currentPath === "/contact" ? "page" : undefined}>
                  <div className={"button-text-wrap"}>
                    <div className={"button-hover-text"}>Schedule a Call</div>
                    <div className={"button-normal-text"}>Schedule a Call</div>
                  </div>
                  <div className={"button-icon-box"}>
                    <div button-icon-anin-one={"ture"} className={"button-icon-wrap"}>
                      <img src={"/assets/shared/arrow-1.svg"} loading={"lazy"} alt={"Icon"} className={"button-icon"} />
                    </div>
                  </div>
                </a>
              </div>
              <div className={"menu-button"}>
                <div className={"hamburger"}>
                  <div data-wf-target={"[[[\"24ca57b6-65bd-90cf-29f6-88f79a1acfa1\",\"24ca57b6-65bd-90cf-29f6-88f79a1acfb1\"],[\"d070b473-1fe1-b6ed-50f6-5caea2049f58\"]]]"} className={"hamburger-line-top"} />
                  <div data-wf-target={"[[[\"24ca57b6-65bd-90cf-29f6-88f79a1acfa1\",\"24ca57b6-65bd-90cf-29f6-88f79a1acfb2\"],[\"d070b473-1fe1-b6ed-50f6-5caea2049f58\"]]]"} className={"hamburger-line-middle"} />
                  <div data-wf-target={"[[[\"24ca57b6-65bd-90cf-29f6-88f79a1acfa1\",\"24ca57b6-65bd-90cf-29f6-88f79a1acfb3\"],[\"d070b473-1fe1-b6ed-50f6-5caea2049f58\"]]]"} className={"hamburger-line-bottom"} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
