// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import StudyInfoSection from "@/components/sites/relab-0c02b053/case-studies-glowskin-launch-7768a6cf/StudyInfoSection";
import CaseDetailSection from "@/components/sites/relab-0c02b053/case-studies-glowskin-launch-7768a6cf/CaseDetailSection";
import OurTalentSection from "@/components/sites/relab-0c02b053/case-studies-glowskin-launch-7768a6cf/OurTalentSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/case-studies-glowskin-launch-7768a6cf/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-glowskin-launch-7768a6cf/ix.json";

export const metadata: Metadata = {
  title: "GlowSkin Launch",
  description: "A creator-first product launch that generated millions of impressions through authentic beauty content.",
  openGraph: {
    title: "GlowSkin Launch",
    description: "A creator-first product launch that generated millions of impressions through authentic beauty content.",
    images: ["/assets/case-studies/01-case-studies/frame-2147262233-2.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies/glowskin-launch"} />
      <StudyInfoSection />
      <CaseDetailSection />
      <OurTalentSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/case-studies/glowskin-launch"} />
      <SiteFooter currentPath={"/case-studies/glowskin-launch"} />
      <PageInteractions payload={ixPayload} route={"/case-studies/glowskin-launch"} />
    </>
  );
}
