// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import PricingPlansSection from "@/components/sites/relab-0c02b053/pricing-7394a2bb/PricingPlansSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/pricing-7394a2bb/ix.json";

export const metadata: Metadata = {
  title: "Pricing - Relab Webflow HTML Website Template",
  description: "Present your plans with the Relab Pricing page, a clean Webflow layout designed to organize packages, features, pricing details, and calls to action.",
  openGraph: {
    title: "Pricing - Relab Webflow HTML Website Template",
    description: "Present your plans with the Relab Pricing page, a clean Webflow layout designed to organize packages, features, pricing details, and calls to action.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009c/6aad1684503d1bf2692ca802_Thumbnail.jpg"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/pricing"} />
      <PricingPlansSection />
      <SiteCta currentPath={"/pricing"} />
      <SiteFooter currentPath={"/pricing"} />
      <PageInteractions payload={ixPayload} route={"/pricing"} />
    </>
  );
}
