// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import BlogDetailSection from "@/components/sites/relab-0c02b053/blogs-what-consumers-actually-want-to-watch-today-5e689f3c/BlogDetailSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/blogs-what-consumers-actually-want-to-watch-today-5e689f3c/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/blogs-what-consumers-actually-want-to-watch-today-5e689f3c/ix.json";

export const metadata: Metadata = {
  title: "What Consumers Actually Want To Watch Today",
  description: "Read thoughtful perspectives, uncover new trends, and discover practical strategies to inspire progress and spark new ideas.",
  openGraph: {
    title: "What Consumers Actually Want To Watch Today",
    description: "Read thoughtful perspectives, uncover new trends, and discover practical strategies to inspire progress and spark new ideas.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009e/6aa634709d6eda94f1a41ab4_image%2019271.avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/blogs/what-consumers-actually-want-to-watch-today"} />
      <BlogDetailSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/blogs/what-consumers-actually-want-to-watch-today"} />
      <SiteFooter currentPath={"/blogs/what-consumers-actually-want-to-watch-today"} />
      <PageInteractions payload={ixPayload} route={"/blogs/what-consumers-actually-want-to-watch-today"} />
    </>
  );
}
