// Generated by scripts/convert-page.mjs from the captured reference markup.
import type { Metadata } from "next";
import "./critical.css";
import SiteHeader from "@/components/sites/relab-0c02b053/shared/SiteHeader";
import StudyInfoSection from "@/components/sites/relab-0c02b053/case-studies-urban-streetwear-72d50848/StudyInfoSection";
import CaseDetailSection from "@/components/sites/relab-0c02b053/case-studies-urban-streetwear-72d50848/CaseDetailSection";
import OurTalentSection from "@/components/sites/relab-0c02b053/case-studies-urban-streetwear-72d50848/OurTalentSection";
import FeaturedCreatorsSection from "@/components/sites/relab-0c02b053/case-studies-urban-streetwear-72d50848/FeaturedCreatorsSection";
import SiteCta from "@/components/sites/relab-0c02b053/shared/SiteCta";
import SiteFooter from "@/components/sites/relab-0c02b053/shared/SiteFooter";
import PageInteractions from "@/components/sites/relab-0c02b053/shared/PageInteractions";
import ixPayload from "@/components/sites/relab-0c02b053/case-studies-urban-streetwear-72d50848/ix.json";

export const metadata: Metadata = {
  title: "Urban Streetwear",
  description: "Lifestyle creators helped the brand boost engagement and drive awareness with short-form video storytelling.",
  openGraph: {
    title: "Urban Streetwear",
    description: "Lifestyle creators helped the brand boost engagement and drive awareness with short-form video storytelling.",
    images: ["https://cdn.prod.website-files.com/6a97e757adfa59f93a89009e/6aad1109ef9322d53f42b675_Frame%202147262233%20(3)%20(1).avif"],
  },
};

export default function Page() {
  return (
    <>
      <SiteHeader currentPath={"/case-studies/urban-streetwear"} />
      <StudyInfoSection />
      <CaseDetailSection />
      <OurTalentSection />
      <FeaturedCreatorsSection />
      <SiteCta currentPath={"/case-studies/urban-streetwear"} />
      <SiteFooter currentPath={"/case-studies/urban-streetwear"} />
      <PageInteractions payload={ixPayload} route={"/case-studies/urban-streetwear"} />
    </>
  );
}
